gamma: 0.95
lr: 0.0005
batch_size: 64
buffer_size: 2000

learner_log_interval: 25000
log_interval: 25000
runner_log_interval: 25000
test_interval: 25000
test_nepisode: 50
test_greedy: True
t_max: 2050000

epsilon_anneal_time: 5000

target_update_interval_or_tau: 200

global_reward: False

name: "IMPc100_ExpoComm"