env: MAgent_TigerDeer
env_args:
  map_size: 45
  max_cycles: 300
  seed: 42
  deer_policy: flee
  state_grid_size: 9
  global_reward: true
  minimap_mode: false
  tiger_step_recover: -0.1
  deer_attacked: -0.1
